/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface BasicEscrowInterface extends Interface {
    getFunction(nameOrSignature: "agent" | "amount" | "buyer" | "confirmDelivery" | "currentStatus" | "deposit" | "refundToBuyer" | "releaseToSeller" | "seller"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'agent', values?: undefined): string;
encodeFunctionData(functionFragment: 'amount', values?: undefined): string;
encodeFunctionData(functionFragment: 'buyer', values?: undefined): string;
encodeFunctionData(functionFragment: 'confirmDelivery', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentStatus', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'refundToBuyer', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseToSeller', values?: undefined): string;
encodeFunctionData(functionFragment: 'seller', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'agent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'amount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmDelivery', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refundToBuyer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseToSeller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seller', data: BytesLike): Result;
  }

  

  export interface BasicEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): BasicEscrow;
    waitForDeployment(): Promise<this>;

    interface: BasicEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    agent: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    amount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    buyer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    confirmDelivery: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    currentStatus: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    refundToBuyer: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    releaseToSeller: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    seller: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'agent'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'amount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buyer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'confirmDelivery'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'currentStatus'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'refundToBuyer'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'releaseToSeller'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'seller'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }