/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface BankInterface extends Interface {
    getFunction(nameOrSignature: "balances" | "deposit" | "drain" | "re" | "totalBalance" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "depositSuccessful"): EventFragment;

    encodeFunctionData(functionFragment: 'balances', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'deposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'drain', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 're', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'balances', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'drain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 're', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace depositSuccessfulEvent {
      export type InputTuple = [sent: string, amount: BigNumberish];
      export type OutputTuple = [sent: string, amount: bigint];
      export interface OutputObject {sent: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Bank extends BaseContract {
    
    connect(runner?: ContractRunner | null): Bank;
    waitForDeployment(): Promise<this>;

    interface: BankInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    balances: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [],
      [boolean],
      'payable'
    >
    

    
    drain: TypedContractMethod<
      [recepient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    re: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'balances'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [],
      [boolean],
      'payable'
    >;
getFunction(nameOrSignature: 'drain'): TypedContractMethod<
      [recepient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 're'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'depositSuccessful'): TypedContractEvent<depositSuccessfulEvent.InputTuple, depositSuccessfulEvent.OutputTuple, depositSuccessfulEvent.OutputObject>;

    filters: {
      
      'depositSuccessful(string,uint256)': TypedContractEvent<depositSuccessfulEvent.InputTuple, depositSuccessfulEvent.OutputTuple, depositSuccessfulEvent.OutputObject>;
      depositSuccessful: TypedContractEvent<depositSuccessfulEvent.InputTuple, depositSuccessfulEvent.OutputTuple, depositSuccessfulEvent.OutputObject>;
    
    };
  }